	
CREATE TABLE registeration_meter_table (
			REGISTER_ID INTEGER NOT NULL, 
			USER_NAME VARCHAR(255), 
			FIRST_NAME VARCHAR(255),
			LAST_NAME VARCHAR(255),
			PASSWORD VARCHAR(255), 
			CONTACT_NUMBER VARCHAR(255), 
			ROLE VARCHAR(255), 
			ADDRESS VARCHAR(255),
			STATE VARCHAR(255),
			COUNTRY VARCHAR(255),
			DISTRICT VARCHAR(255),
			PINCODE VARCHAR(255),
			PURCHASE_TYPE VARCHAR(255),
			GST_NUMBER VARCHAR(255),
			CUSTOMER_COMPANY VARCHAR(255), 
			CONSTRAINT PK_REGISTER_ID PRIMARY KEY(REGISTER_ID)
);

CREATE TABLE rent_meter_table (
			CUSTOMER_ID INTEGER NOT NULL, 
			CUSTOMER_EMAIL VARCHAR(255), 
			CUSTOMER_PHONENUMBER VARCHAR(255), 
			CONTACT_NUMBER VARCHAR(255), 
			AMOUNT VARCHAR(255), 
			ORDER_STATUS VARCHAR(255),
			ADDRESS VARCHAR(255),
			STATE VARCHAR(255),
			COUNTRY VARCHAR(255),
			DISTRICT VARCHAR(255),
			PINCODE VARCHAR(255),
			METER_NAME VARCHAR(255), 
			ORDER_ID VARCHAR(255), 
			CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY(CUSTOMER_ID)
);